postgres:
  image: postgres:latest
  ports:
    - '5432:5432'
  environment:
    POSTGRES_USER: 'user'
    POSTGRES_PASSWORD: 'password'
    POSTGRES_DB: 'ipport'
  volumes:
    - ./init:/docker-entrypoint-initdb.d/

# sudo docker-compose up -d
